config/routes.rb
Railsgirls::Application.routes.draw do
  resources :mail_templates
  root  'static_pages#home', as: :home
  resources :sessions, only: [:new, :create, :destroy]
  match '/registrations/new_coach', to: 'registrations#new_coach',  via: 'get', as: :new_coach
  resources :registrations
  resources :users
  match '/admin',  to: 'sessions#new',         via: 'get', as: :admin
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/success_reg', to: 'registrations#success_reg',  via: 'get', as: :success_reg
  resources :workshops, :except => [:show]
  get 'forms/:id' => 'forms#show', as: :coach_form
  get 'forms/:id' => 'forms#show', as: :participant_form
  get 'forms/:type/new' => 'forms#new', as: :new_form
  resources :forms
  get 'workshops/:id/publish' => 'workshops#publish'
  get 'workshops/:id/unpublish' => 'workshops#unpublish'
  post 'workshops/addForm' => 'workshops#addForm'
  post 'workshops/add_mail_template' => 'workshops#add_mail_template'
  post 'workshops/manual_mail_send' => 'workshops#manual_mail_send'
  get 'workshops/manual_mail_show/' => 'workshops#manual_mail_show'
  post 'registrations/accept_registrations' => 'registrations#accept_registrations'

  

end

app/models/workshop.rb
class Workshop
  include MongoMapper::Document
  plugin MongoMapper::Plugins::MultiParameterAttributes

  key :name,				String
  key :description,			String
  key :date,				Date
  key :venue,				String
  key :published,		Boolean

  one :mail_template
  one :coach_form
  one :participant_form

  timestamps!
end

app/controllers/workshops_controller.rb
require 'active_support'

class WorkshopsController < ApplicationController

  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :create, :index, :edit, :update, :show]
  # GET /workshops
  def index
    @workshops = Workshop.all
    @forms = Form.all
    @mail_templates = MailTemplate.all
  end

  def publish
    @workshop = Workshop.find(params[:id])
    if (@workshop.participant_form != nil)
      @workshop.published = true
      @workshop.save
      redirect_to edit_workshop_path(@workshop), notice: 'Workshop was successfully published.'
    else
      redirect_to edit_workshop_path(@workshop), notice: 'Workshop could not be published. Please create a participant form!'
    end
  end

  def unpublish
    @workshop = Workshop.find(params[:id])
    @workshop.published = false
    @workshop.save
    redirect_to edit_workshop_path(@workshop), notice: 'Workshop was successfully unpublished.'
  end

  def addForm
    @existing_form = Form.find(params[:id])
    @workshop = Workshop.find(params[:workshop_id])
    if params[:type] == "coach"
      @form = CoachForm.new
      @key = SecureRandom.hex
      @workshop.update_attributes!(:coach_key => @key)
    else
      @form = ParticipantForm.new
    end
    @form.workshop_id = params[:workshop_id]
    @form.structure = @existing_form.structure
    if @form.save
      redirect_to workshops_url, notice: 'Workshop was successfully updated.'
    else
      redirect_to workshops_url, notice: 'Could not update Workshop.'
    end
  end

  def add_mail_template
    @existing_mail_template = MailTemplate.find(params[:id])
    @workshop = Workshop.find(params[:workshop_id])
    @mail_template = MailTemplate.new
    @mail_template.workshop_id = params[:workshop_id]
    @mail_template.name = @existing_mail_template.name
    @mail_template.subject = @existing_mail_template.subject
    @mail_template.text = @existing_mail_template.text

    if @mail_template.save
      redirect_to workshops_url, notice: 'Workshop was successfully updated.'
    else
      redirect_to workshops_url, notice: 'Could not update Workshop.'
    end
  end

  def manual_mail_show

  end

  def manual_mail_send
    mail_template = MailTemplate.create(:name => params[:name], :subject => params[:subject], :text => params[:text])
    mail_template.workshop = Workshop.find(params[:workshop][:id])

    RegistrationMailer.manual_email(mail_template, get_receiptments_from_params(params)).deliver
    redirect_to workshops_url, notice: 'E-Mail was successfully sent.'
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  def create
    @workshop = Workshop.new(workshop_params)
    standard_mail_template = MailTemplate.create(:workshop_id => @workshop.id)
    if @workshop.save
      redirect_to workshops_path, notice: 'Workshop was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /workshops/1
  def update
    if @workshop.update_attributes(workshop_params)
      redirect_to workshops_url, notice: 'Workshop was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /workshops/1
  def destroy
    @workshop.destroy
    redirect_to workshops_url, notice: 'Workshop was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Before filters
    def signed_in_user
      store_location
      redirect_to admin_path, notice: "Only for Admins available! Please sign in." unless signed_in?
    end

    # Only allow a trusted parameter "white list" through.
    def workshop_params
      params.require(:workshop).permit(:name, :date, :description, :venue)
    end

    def get_receiptments_from_params(params)
      workshop = Workshop.find(params['workshop']['id'])
      receipments = []
      if params["admins"]
        User.all.each do |user|
          receipments.push user.email
        end
      end
      if params["participants"]
        workshop.participant_form.registrations.each do |registration|
          receipments.push registration.email
        end
      end
      if params["coach"]
        workshop.coach_form.registrations.each do |registration|
          receipments.push registration.email
        end
      end
      if params["participants_accepted"]
        workshop.participant_form.registrations.find_all_by_accepted(true).each do |registration|
          receipments.push registration.email
        end
      end
      if params["participants_rejected"]
        workshop.participant_form.registrations.all(:accepted.ne => true).each do |registration|
          receipments.push registration.email
        end
      end
      receipments
    end
end

app/helpers/workshop_helper.rb
module WorkshopHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_for(@workshop) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% @workshop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_area :venue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workshops/_form_manual_mail.erb
<%= form_tag "/workshops/manual_mail_send" do %>

<h2>You can use the following tags within the email-body:</h2>
<ul class="textlist">
  <li><p>[workshop_name]</p></li>
  <li><p>[workshop_description]</p></li>
  <li><p>[workshop_date]</p></li>
  <li><p>[workshop_venue]</p></li>
</ul>

  <%= label_tag "name for future reuse"%>
  <%= text_field_tag "name"%>
  <%= label_tag "Receipments"%>
  <span>all admins in bcc</span>
  <%= check_box_tag 'admins', '1'%>
  <span>all participants in bcc</span>
  <%= check_box_tag 'participants', '1'%>
  <span>all coaches in bcc</span>
  <%= check_box_tag 'coaches', '1'%>
  <span>all accepted participants in bcc</span>
  <%= check_box_tag 'participants_accepted', '1'%>
  <span>all rejected participants in bcc</span>
  <%= check_box_tag 'participants_rejected', '1'%>

  <%= label_tag "email subject"%>
  <%= text_field_tag "subject"%>
  <%= label_tag "email text"%>
  <%= text_area_tag "text"%>
  <%= submit_tag "Send" %>
  <input name="workshop[id]" type="hidden" value="<%= params["id"]%>" />
<% end %>

app/views/workshops/edit.html.erb
<%workshop = Workshop.find(params[:id]) %>

<h1><%=workshop.name%> <%=workshop.date%></h1>
<h1 id="workshop_navi"><% if !workshop.published and !workshop.participant_form.nil? %>
<%= link_to "publish", { :controller => "workshops", :action => "publish", :id=>workshop.id} do %><i class="fa fa-eye"></i> publish workshop<% end %>
<% else %>
<%= link_to "unpublish", { :controller => "workshops", :action => "unpublish", :id=>workshop.id} do %><i class="fa fa-eye-slash"></i> unpublish workshop<% end %>
<% end %><br>
<%= link_to registrations_path(:workshop=>workshop.id), :title=>"Show Registrations" do %><i class="fa fa-arrow-right"></i> show registrations<% end %></h1>

<div class="workshop_show_form_box">
	<div class="participant_box">
  <% if workshop.participant_form != nil %>
    <%= link_to edit_form_path(workshop.participant_form.id), :title=>"Edit Participant Form" do %><i class="fa fa-pencil"> Edit Participant Form</i><% end %><br />
    <%= link_to new_registration_path(:id=>workshop.id, :type=>:participant), :title=>"Participant Registration Link" do %><i class="fa fa-arrow-right"></i> Participant Registration Link<% end %>
  <% else %>
    <%= link_to new_form_path(:type => :participant, :workshop_id => workshop.id), :title=>'Add Participant Form' do %><i class="fa fa-plus"></i><br /> Add Participant Form<% end %>
    <% if @forms.count > 0 %>
      <%= link_to forms_path(:id=>workshop.id, :type=>"participant"), :title=>'Add excisting Participant Form' do %><i class="fa fa-plus"></i> Add excisting Participant Form<% end %>
    <% end %>
  <% end %>
  </div>
  <div class="coachBox">
  <% if workshop.coach_form != nil %>
    <%= link_to edit_form_path(workshop.coach_form.id), :title=>"Edit Coach Form" do %><i class="fa fa-pencil"></i> Edit Coach Form<% end %><br />
  <% else %>
    <%= link_to new_form_path(:type => :coach, :workshop_id => workshop.id), :title=>'Add Coach Form' do %>
    <i class="fa fa-plus"></i> Add Coach Form<% end %><br />
    <% if @forms.count > 0 %>
      <%= link_to forms_path(:id=>workshop.id, :type=>"coach"), :title=>'Add existing Coach Form' do %><i class="fa fa-plus"></i> Add existing Coach Form<% end %>
    <% end %>
  <% end %>
  <% if workshop.keys.include? "coach_key" %>
    <%= link_to new_registration_path(:id=>workshop.id, :type=>"coach",:coach_key=>workshop.coach_key), :title=>"Coach Registration Link" do %><i class="fa fa-arrow-right"></i> Coach Registration Link<% end %>
  <% end %>
  </div>
</div>

<%= render 'form' %>

<div class="workshop_show_mail_box">
  <% if workshop.mail_template != nil %>
    <%= link_to edit_mail_template_path(workshop.mail_template.id), :title=>"Edit Mail Template" do %><i class="fa fa-pencil"></i> Edit Mail Template for automatic Email confirmations after every registration<% end %><br />
  <% else %>
    <%= link_to new_mail_template_path(:workshop_id => workshop.id), :title=>'Add Mail Template' do %><i class="fa fa-plus"></i><br /> Add Mail Template for automatic Email confirmations after every registration<% end %>
    <% if @mail_templates.count > 0 %>
      <%= link_to mail_templates_path(:workshop_id => workshop.id), :title=>'Add excisting Mail Template' do %><i class="fa fa-plus"></i> Existing<% end %>
    <% end %>
  <% end %>
	<%= link_to workshops_manual_mail_show_path(:id => workshop.id), :title=>'New Mail' do %><i class="fa fa-plus"></i>Send Email to multiple participants, coaches or admins<% end %>
</div>

app/views/workshops/index.html.erb
<h1>Listing workshops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Description</th>
      <th>Venue</th>
      <th class="settings">Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.name %></td>
        <td><%= workshop.date %></td>
        <td><%= workshop.description %></td>
        <td><%= workshop.venue %></td>
        <td>
          <%= link_to edit_workshop_path(workshop), :title=>"Edit" do %><i class="fa fa-pencil"></i><% end %>
          <%= link_to workshop, method: :delete, data: { confirm: 'Are you sure?' }, :title=>"Destroy" do %><i class="fa fa-trash-o"></i>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

app/views/workshops/manual_mail_show.erb
<h1>New Manual Mail</h1>

<%= render 'form_manual_mail' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/new.html.erb
<h1>New workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<% provide(:title, 'Workshop') %>

<table>
  <thead>
    <tr>
      <% if @workshop != nil
         @workshop.attributes.each do |attr_name, attr_value| %>
          <% if attr_name != '_id' and attr_name != 'authenticity_token' %>
            <p>
              <strong><%= attr_name %>: </strong><%= attr_value %>
            </p>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  </thead>
</table>
<%= link_to 'Back', :back %>