config/routes.rb
Railsgirls::Application.routes.draw do
  resources :mail_templates
  root  'static_pages#home', as: :home
  resources :sessions, only: [:new, :create, :destroy]
  match '/registrations/new_coach', to: 'registrations#new_coach',  via: 'get', as: :new_coach
  resources :registrations
  resources :users
  match '/admin',  to: 'sessions#new',         via: 'get', as: :admin
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/success_reg', to: 'registrations#success_reg',  via: 'get', as: :success_reg
  resources :workshops, :except => [:show]
  get 'forms/:id' => 'forms#show', as: :coach_form
  get 'forms/:id' => 'forms#show', as: :participant_form
  get 'forms/:type/new' => 'forms#new', as: :new_form
  resources :forms
  get 'workshops/:id/publish' => 'workshops#publish'
  get 'workshops/:id/unpublish' => 'workshops#unpublish'
  post 'workshops/addForm' => 'workshops#addForm'
  post 'workshops/add_mail_template' => 'workshops#add_mail_template'
  post 'workshops/manual_mail_send' => 'workshops#manual_mail_send'
  get 'workshops/manual_mail_show/' => 'workshops#manual_mail_show'
  post 'registrations/accept_registrations' => 'registrations#accept_registrations'

  

end

app/controllers/forms_controller.rb
require 'json'

class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  def index
    @forms = Form.all
    @structure = []
    @forms.each do |form|
      @structure.push JSON.parse form.structure
    end
  end

  # GET /forms/1
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
    @structure = []
    @structure.push "type"=>"text", "caption"=>"Firstname", "name"=>"firstname", "class"=>"immutable_element"
    @structure.push "type"=>"text", "caption"=>"Lastname", "name"=>"lastname", "class"=>"immutable_element"
    @structure.push "type"=>"text", "caption"=>"E-Mail", "name"=>"email", "class"=>"immutable_element"
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  def create
    workshop_id = form_params[:workshop_id]
    @workshop = Workshop.find(workshop_id)
    if form_params[:type] == "coach"
      @form = CoachForm.new(form_params)
      if @workshop != nil
        @key = SecureRandom.hex
        @workshop.update_attributes!(:coach_key => @key)
      end
    else
      @form = ParticipantForm.new(form_params)
    end
    @form.workshop_id = workshop_id
    if @form.save
      redirect_to workshops_path, notice: 'Form was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /forms/1
  def update
    @form = Form.find_by_id(params[:id])
    if @form.update_attributes(form_params)
      redirect_to @form, notice: 'Form was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /forms/1
  def destroy
    @form.destroy
    if @form.workshop != nil
      @form.workshop.published = false
      @form.workshop.save
    end
    redirect_to forms_url, notice: 'Form was successfully destroyed. Due to this, the corresponding Workshop is no longer published'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def form_params
      params[:form]
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<div id="structure_forms" style="display:none">
  
  <div class="structure text">
  </div>

  <div class="structure textarea">
  </div>

  <div class="structure checkbox">
  </div>

  <div class="structure radiobuttons">
    
    <a href="" class="add_option">Add Option</a>
    <input style="display:none;" type="text" name="options" value='{"yes":"Yes","no":"No"}'>
  </div>

</div>


<h2>Add Form Element</h2>
<form id="add_structure">

  <select name="type" id="type">
    <option value="text">Text</option>
    <option value="checkbox">Checkbox</option>
    <option value="radiobuttons">Radiobutton</option>
    <option value="textarea">Textarea</option>
  </select>

  <label for="caption">Caption</label>
  <input type="text" name="caption" id="caption" required>

  <div id="current_structure_form">
  </div>

  <button type="submit" class="submit">add to structure</button>
</form>

<h2>Form Preview</h2>
<form id="form_preview" class="editable"></form>


<%= form_for(@form) do |f| %>
  <%= hidden_field(:form, :structure) %>

  <input name="form[type]" type="hidden" value="<%= params["type"] || @form._type %>" />
  <input name="form[workshop_id]" type="hidden" value="<%= @form.workshop_id || params["workshop_id"] %>" />
  <div class="actions">
    <%= f.submit "Save Form" %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<script type="text/javascript">
	structure_to_render = <%= @form.structure.html_safe %>;
</script>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<% workshop = Workshop.find(params[:id]) 
  i = 0
%>
<h1>Listing forms</h1>

<% @forms.each do |form| %>
  <%= link_to form_path(form, :workshop_id=>params[:id], :type=>params[:type]), :title=>"Show Participant Form" do %><div class = "form_preview_card">
    <strong>Previously used for:</strong><br>
    <span>Name: <%=workshop.name%></span><br>
    <span>Date: <%=workshop.date%></span><br>
    <ul>
      <% if @structure[i].count >= 4 %>
        <li><%=@structure[i][3]["caption"][0..45]%>
        <%if @structure[i][3]["caption"].length > 45%>
            ...
        <%end%>
        </li>
      <% end %>
      <% if @structure[i].count >= 5 %>
        <li><%=@structure[i][4]["caption"][0..45]%>
        <%if @structure[i][4]["caption"].length > 45%>
            ...
        <%end%>
        </li>
      <% end %>
      <% if @structure[i].count >= 6 %>
        <li><%=@structure[i][5]["caption"][0..45]%>
        <%if @structure[i][5]["caption"].length > 45%>
            ...
        <%end%>
        </li>
      <% end %>
    </ul>
    <span>Form has <%=@structure[i].count%> inputfields.</span>
    <br><%= link_to form_path(form), method: :delete, data: { confirm: 'Are you sure?' }, :title=>"Destroy" do %><i class="fa fa-trash-o"></i><% end %>

  </div>
  <% end %>
  <% i+=1 %>
<% end %>

app/views/forms/new.html.erb
<h1>New form</h1>

<script type="text/javascript">
	structure_to_render = <%= @structure.to_json.html_safe %>;
</script>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<script type="text/javascript">
	structure_to_render = <%= @form.structure.html_safe %>;
</script>

<form id="form_preview"></form>

<%= link_to form_path(params[:id]), method: :delete, data: { confirm: 'Are you sure?' }, :title=>"Destroy" do %><i class="fa fa-trash-o"></i><% end %>

<% if params[:workshop_id] != nil %>
    <%= button_to "Add to Workshop", { :controller => "workshops", :action => "addForm", :id=>params[:id], :type=>params[:type], :workshop_id=>params[:workshop_id]}%>
<% end %>

<%= link_to 'Back', forms_path %>