config/routes.rb
Railsgirls::Application.routes.draw do
  resources :mail_templates
  root  'static_pages#home', as: :home
  resources :sessions, only: [:new, :create, :destroy]
  match '/registrations/new_coach', to: 'registrations#new_coach',  via: 'get', as: :new_coach
  resources :registrations
  resources :users
  match '/admin',  to: 'sessions#new',         via: 'get', as: :admin
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/success_reg', to: 'registrations#success_reg',  via: 'get', as: :success_reg
  resources :workshops, :except => [:show]
  get 'forms/:id' => 'forms#show', as: :coach_form
  get 'forms/:id' => 'forms#show', as: :participant_form
  get 'forms/:type/new' => 'forms#new', as: :new_form
  resources :forms
  get 'workshops/:id/publish' => 'workshops#publish'
  get 'workshops/:id/unpublish' => 'workshops#unpublish'
  post 'workshops/addForm' => 'workshops#addForm'
  post 'workshops/add_mail_template' => 'workshops#add_mail_template'
  post 'workshops/manual_mail_send' => 'workshops#manual_mail_send'
  get 'workshops/manual_mail_show/' => 'workshops#manual_mail_show'
  post 'registrations/accept_registrations' => 'registrations#accept_registrations'

  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
      <%= image_tag(settings.logoURL) %>
        <ul class="nav pull-right">          
          <% if signed_in? %>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
            <li>
              <%= link_to "Show Registrations", registrations_path%>
            </li>
            <li>
              <%= link_to "Workshops", workshops_path %>
            </li>
          <% end %>
          <li>
            <%= link_to "Home", home_path %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>